import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Aura808LogDrum } from '@/components/plugins/Aura808LogDrum';
import { UnifiedAnalysisPanel } from '@/components/UnifiedAnalysisPanel';
import { usePluginSystem } from '@/hooks/usePluginSystem';
import { Music2, Headphones, Zap, Settings, Brain } from 'lucide-react';

export default function Aura808Demo() {
  const [audioContext, setAudioContext] = useState<AudioContext | null>(null);
  const [isInitialized, setIsInitialized] = useState(false);
  const pluginSystem = usePluginSystem(audioContext);

  useEffect(() => {
    // Initialize audio context on user interaction
    const initAudio = () => {
      if (!audioContext) {
        const context = new AudioContext();
        setAudioContext(context);
        setIsInitialized(true);
      }
    };

    // Auto-initialize for demo purposes
    initAudio();
  }, [audioContext]);

  const handleParameterChange = (parameterId: string, value: number) => {
    console.log(`Parameter ${parameterId} changed to:`, value);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background/95 to-primary/5">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <div className="text-4xl">🥁</div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
              Aura 808 Log Drum
            </h1>
          </div>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Experience the authentic sound of Amapiano with our AI-powered hybrid synth-sampler engine.
            Designed for producers who demand cultural authenticity and professional quality.
          </p>
        </div>

        {/* Features Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <Card className="text-center">
            <CardHeader>
              <Music2 className="h-8 w-8 text-primary mx-auto mb-2" />
              <CardTitle className="text-lg">Hybrid Engine</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Combines sine wave synthesis with authentic log drum samples for genuine Amapiano character
              </p>
            </CardContent>
          </Card>

          <Card className="text-center">
            <CardHeader>
              <Zap className="h-8 w-8 text-primary mx-auto mb-2" />
              <CardTitle className="text-lg">AI Presets</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Genre-specific presets generated by AI for Amapiano, Private School, and Deep House styles
              </p>
            </CardContent>
          </Card>

          <Card className="text-center">
            <CardHeader>
              <Settings className="h-8 w-8 text-primary mx-auto mb-2" />
              <CardTitle className="text-lg">Full Control</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Complete ADSR envelope, pitch glide, body/knock mixing, and real-time visualization
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Demo Section */}
        <Tabs defaultValue="demo" className="mb-8">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="demo">Interactive Demo</TabsTrigger>
            <TabsTrigger value="analysis" className="flex items-center gap-2">
              <Brain className="w-4 h-4" />
              Sound Analysis
            </TabsTrigger>
          </TabsList>

          <TabsContent value="demo">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Headphones className="h-5 w-5" />
                    Interactive Demo
                  </CardTitle>
                  <div className="flex items-center gap-2">
                    <Badge variant={isInitialized ? 'default' : 'secondary'}>
                      {isInitialized ? 'Audio Ready' : 'Initializing...'}
                    </Badge>
                    {audioContext && (
                      <Badge variant="outline">
                        {audioContext.sampleRate / 1000}kHz
                      </Badge>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {isInitialized ? (
                  <Aura808LogDrum
                    audioContext={audioContext}
                    onParameterChange={handleParameterChange}
                    trackId="demo-track"
                  />
                ) : (
                  <div className="text-center py-12">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
                    <p className="text-muted-foreground">Initializing audio engine...</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="analysis">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Brain className="h-5 w-5" />
                  Analyze Your Sounds
                </CardTitle>
              </CardHeader>
              <CardContent>
                <UnifiedAnalysisPanel 
                  showOptions={true}
                  onAnalysisComplete={(result) => {
                    console.log('Aura808 analysis complete:', result);
                  }}
                />
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Technical Specifications */}
        <Card>
          <CardHeader>
            <CardTitle>Technical Specifications</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h4 className="font-semibold mb-3">Sound Generation</h4>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Hybrid synth-sampler architecture</li>
                  <li>• 808-style sine wave oscillator</li>
                  <li>• Authentic log drum sample layering</li>
                  <li>• Real-time pitch glide with exponential curves</li>
                  <li>• Separate body and knock mix controls</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Controls & Features</h4>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Full ADSR envelope shaping</li>
                  <li>• Real-time waveform visualization</li>
                  <li>• AI-generated genre-specific presets</li>
                  <li>• MIDI note range: C1 to C7</li>
                  <li>• Sub-bass optimized filtering</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="text-center mt-8 py-6 border-t">
          <p className="text-sm text-muted-foreground">
            Built with the AURA-X Plugin SDK • Powered by Web Audio API • Culturally Authentic
          </p>
        </div>
      </div>
    </div>
  );
}