/**
 * DJ Set Export Utilities
 * - Cue Sheet PDF generation
 * - Mix export (WAV via OfflineAudioContext)
 * - Tracklist clipboard copy
 */

import jsPDF from 'jspdf';
import { GeneratedSet, PRESET_INFO } from './DJAgentTypes';
import { toast } from 'sonner';

/**
 * Generate and download a PDF cue sheet
 */
export function exportCueSheet(set: GeneratedSet) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(set.name, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const presetLabel = PRESET_INFO[set.preset]?.label || set.preset;
  const totalMin = Math.round(set.durationSec / 60);
  doc.text(`Preset: ${presetLabel} | Duration: ${totalMin} min | Tracks: ${set.tracklist.length}`, pageWidth / 2, y, { align: 'center' });
  y += 8;

  // Scores
  doc.setFontSize(9);
  doc.text(`Scores — Overall: ${set.scores.overall} | Energy: ${set.scores.energySmoothness} | Transitions: ${set.scores.transitionCleanliness} | Harmonic: ${set.scores.harmonicClash} | Novelty: ${set.scores.novelty}`, pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Table header
  doc.setFillColor(30, 30, 30);
  doc.setTextColor(255, 255, 255);
  doc.rect(14, y - 4, pageWidth - 28, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('#', 16, y);
  doc.text('Time', 24, y);
  doc.text('Track', 48, y);
  doc.text('Artist', 120, y);
  doc.text('BPM', 160, y);
  doc.text('Key', 178, y);
  y += 8;

  // Table rows
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');

  const trackItems = set.items.filter(i => i.type === 'track');
  const transitionItems = set.items.filter(i => i.type === 'transition');

  for (let i = 0; i < set.tracklist.length; i++) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const t = set.tracklist[i];
    
    // Alternating row bg
    if (i % 2 === 0) {
      doc.setFillColor(245, 245, 245);
      doc.rect(14, y - 4, pageWidth - 28, 7, 'F');
    }

    doc.setFontSize(8);
    doc.text(`${i + 1}`, 16, y);
    doc.text(t.time, 24, y);
    doc.text(t.title.substring(0, 40), 48, y);
    doc.text((t.artist || '—').substring(0, 20), 120, y);
    doc.text(`${t.bpm}`, 160, y);
    doc.text(t.key, 178, y);
    y += 7;

    // Transition note
    if (i < transitionItems.length) {
      const trans = transitionItems[i];
      doc.setFontSize(6);
      doc.setTextColor(100, 100, 100);
      const transLabel = (trans.transitionType || 'crossfade').replace(/_/g, ' ');
      doc.text(`   ↳ ${transLabel} (${trans.bars || 16} bars)`, 48, y);
      doc.setTextColor(0, 0, 0);
      y += 5;
    }
  }

  // Footer
  y += 8;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by AURA-X DJ Agent — ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: 'center' });

  doc.save(`${set.name.replace(/[^a-zA-Z0-9]/g, '_')}_cue_sheet.pdf`);
  toast.success('Cue sheet downloaded');
}

/**
 * Export mix as WAV file using OfflineAudioContext
 */
export async function exportMixAsWav(
  set: GeneratedSet,
  trackSources: { id: string; fileUrl: string }[],
  onProgress?: (pct: number) => void
) {
  const DEFAULT_CROSSFADE = 8;
  const EXPORT_SAMPLE_RATE = 44100;
  const trackItems = set.items.filter(i => i.type === 'track');

  if (trackItems.length === 0) {
    toast.error('No tracks to export');
    return;
  }

  toast.info('Rendering mix — this may take a moment...');
  onProgress?.(5);

  // Load and decode one track at a time to prevent OOM
  const decoded: { index: number; buffer: AudioBuffer }[] = [];

  for (let i = 0; i < trackItems.length; i++) {
    const url = trackSources.find(t => t.id === trackItems[i].trackId)?.fileUrl;
    if (!url) continue;
    try {
      const resp = await fetch(url);
      const arrBuf = await resp.arrayBuffer();
      const ctx = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: EXPORT_SAMPLE_RATE });
      const audioBuf = await ctx.decodeAudioData(arrBuf);
      await ctx.close();
      decoded.push({ index: i, buffer: audioBuf });
    } catch (e) {
      console.warn(`[DJ Export] Failed to load track ${i}:`, e);
    }
    onProgress?.(5 + (i / trackItems.length) * 40);
    // Yield to GC between tracks
    await new Promise(r => setTimeout(r, 50));
  }

  if (decoded.length === 0) {
    toast.error('Could not load any audio for export');
    return;
  }

  // Calculate schedule
  let totalDuration = 0;
  const schedules: { buffer: AudioBuffer; startTime: number; crossfadeSec: number; isFirst: boolean; isLast: boolean }[] = [];

  for (let i = 0; i < decoded.length; i++) {
    const { buffer } = decoded[i];
    const crossfadeSec = i < decoded.length - 1 ? Math.min(DEFAULT_CROSSFADE, buffer.duration * 0.3) : 0;
    schedules.push({
      buffer,
      startTime: totalDuration,
      crossfadeSec,
      isFirst: i === 0,
      isLast: i === decoded.length - 1,
    });
    totalDuration += buffer.duration - crossfadeSec;
  }

  onProgress?.(50);

  // Render offline
  const offlineCtx = new OfflineAudioContext(2, Math.ceil(totalDuration * EXPORT_SAMPLE_RATE), EXPORT_SAMPLE_RATE);

  for (const sched of schedules) {
    const source = offlineCtx.createBufferSource();
    source.buffer = sched.buffer;
    const gain = offlineCtx.createGain();
    gain.connect(offlineCtx.destination);
    source.connect(gain);

    if (!sched.isFirst) {
      gain.gain.setValueAtTime(0, sched.startTime);
      gain.gain.linearRampToValueAtTime(1, sched.startTime + sched.crossfadeSec);
    } else {
      gain.gain.setValueAtTime(1, sched.startTime);
    }

    if (!sched.isLast && sched.crossfadeSec > 0) {
      const fadeOutStart = sched.startTime + sched.buffer.duration - sched.crossfadeSec;
      gain.gain.setValueAtTime(1, fadeOutStart);
      gain.gain.linearRampToValueAtTime(0, fadeOutStart + sched.crossfadeSec);
    }

    source.start(sched.startTime);
  }

  onProgress?.(60);

  const renderedBuffer = await offlineCtx.startRendering();
  // Free decoded buffers
  decoded.length = 0;
  schedules.length = 0;
  onProgress?.(85);

  const wav = encodeWAV(renderedBuffer);
  const blob = new Blob([wav], { type: 'audio/wav' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = `${set.name.replace(/[^a-zA-Z0-9]/g, '_')}_mix.wav`;
  a.click();
  URL.revokeObjectURL(url);

  onProgress?.(100);
  toast.success('Mix exported as WAV!');
}

/**
 * Encode AudioBuffer to WAV format
 */
function encodeWAV(buffer: AudioBuffer): ArrayBuffer {
  const numChannels = buffer.numberOfChannels;
  const sampleRate = buffer.sampleRate;
  const format = 1; // PCM
  const bitsPerSample = 16;
  
  const channels: Float32Array[] = [];
  for (let i = 0; i < numChannels; i++) {
    channels.push(buffer.getChannelData(i));
  }
  
  const numSamples = buffer.length;
  const dataLength = numSamples * numChannels * (bitsPerSample / 8);
  const headerLength = 44;
  const totalLength = headerLength + dataLength;
  
  const arrayBuffer = new ArrayBuffer(totalLength);
  const view = new DataView(arrayBuffer);
  
  // RIFF header
  writeString(view, 0, 'RIFF');
  view.setUint32(4, totalLength - 8, true);
  writeString(view, 8, 'WAVE');
  
  // fmt chunk
  writeString(view, 12, 'fmt ');
  view.setUint32(16, 16, true);
  view.setUint16(20, format, true);
  view.setUint16(22, numChannels, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * numChannels * (bitsPerSample / 8), true);
  view.setUint16(32, numChannels * (bitsPerSample / 8), true);
  view.setUint16(34, bitsPerSample, true);
  
  // data chunk
  writeString(view, 36, 'data');
  view.setUint32(40, dataLength, true);
  
  // Interleave and write samples
  let offset = 44;
  for (let i = 0; i < numSamples; i++) {
    for (let ch = 0; ch < numChannels; ch++) {
      const sample = Math.max(-1, Math.min(1, channels[ch][i]));
      view.setInt16(offset, sample < 0 ? sample * 0x8000 : sample * 0x7FFF, true);
      offset += 2;
    }
  }
  
  return arrayBuffer;
}

function writeString(view: DataView, offset: number, str: string) {
  for (let i = 0; i < str.length; i++) {
    view.setUint8(offset + i, str.charCodeAt(i));
  }
}

/**
 * Copy tracklist to clipboard
 */
export function copyTracklistToClipboard(set: GeneratedSet) {
  const lines = set.tracklist.map((t, i) => 
    `${i + 1}. [${t.time}] ${t.title}${t.artist ? ` — ${t.artist}` : ''} (${t.bpm} BPM, ${t.key})`
  );
  const text = `${set.name}\n${'='.repeat(40)}\n${lines.join('\n')}\n\nScores: Overall ${set.scores.overall}/100 | Energy ${set.scores.energySmoothness} | Transitions ${set.scores.transitionCleanliness}`;
  
  navigator.clipboard.writeText(text).then(() => {
    toast.success('Tracklist copied to clipboard');
  }).catch(() => {
    toast.error('Failed to copy');
  });
}
