// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mywijmtszelyutssormy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15d2lqbXRzemVseXV0c3Nvcm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzMzNTMsImV4cCI6MjA3MTgwOTM1M30.oRxFmdyPzA1zgk5K68j5huf3NWbuezEPISnHtngRM8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});